### ISSUE TITLE
Ability to generate JSON schema on fly

### ISSUE THREAD

**Issue by george-oakling** [brainicorn/jsonschemagen#3]
Is there any possibility to generate the schema on fly by Go code? Ideally like this:
`
type MyStruct struct {
   ID string
}

fmt.Print(jsonschemagen.GenerateFromStruct(&MyStruct{}))
`

Thank you :)

**Comment by jdoklovic** [comment]
That's not possible with this tool as this tool uses AST/source code to generate the schemas at build time.
There are other tools that use reflection and can generate schemas at runtime .
